import type { SupabaseClient } from "@supabase/supabase-js";
import { GitOps } from "@conductor/cm-adapters";
import { canTransitionScan } from "@conductor/cm-core";

type CmScanRow = {
  id: string;
  repo_id: string;
  workspace_id: string;
  status: string;
};

type CmRepoRow = {
  id: string;
  owner: string;
  name: string;
  default_branch: string;
};

export async function handlePushAndPR(
  supabase: SupabaseClient,
  scanId: string,
  repoUrl: string,
  gitOps?: GitOps,
): Promise<void> {
  const scanResp = await supabase
    .from("cm_scan")
    .select("*")
    .eq("id", scanId)
    .single() as unknown as { data: CmScanRow | null; error: { message: string } | null };

  if (scanResp.error || !scanResp.data) {
    throw new Error(`Failed to load cm_scan ${scanId}: ${scanResp.error?.message ?? "not found"}`);
  }

  const scan = scanResp.data;

  if (!canTransitionScan(scan.status as never, "pr_opening")) {
    console.log(`[push-pr] scan ${scanId} cannot transition to pr_opening (status=${scan.status})`);
    return;
  }

  const repoResp = await supabase
    .from("cm_repo")
    .select("*")
    .eq("id", scan.repo_id)
    .single() as unknown as { data: CmRepoRow | null; error: { message: string } | null };

  if (repoResp.error || !repoResp.data) {
    throw new Error(`Failed to load cm_repo for scan ${scanId}`);
  }

  const repo = repoResp.data;

  await supabase
    .from("cm_scan")
    .update({ status: "pr_opening", current_step: "Committing fixes and opening PR..." })
    .eq("id", scanId);

  const ops = gitOps ?? new GitOps();
  const workDir = await ops.cloneToTemp(repoUrl);

  try {
    await ops.createBranch(workDir, "checkmarx-auto");

    const { Octokit } = await import("@octokit/rest");
    const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN ?? "" });

    const { data: pr } = await octokit.rest.pulls.create({
      owner: repo.owner,
      repo: repo.name,
      title: `[CM] Auto-fix: Checkmarx findings resolved`,
      body: `## Checkmarx Auto-Fix PR\n\nThis PR was automatically generated by the CM Pipeline.\n\n### Changes\n- Dependency upgrades and/or code fixes applied to resolve Checkmarx findings.\n- All fixes have been verified by the pipeline.\n\n### Testing\n- Fixes were tested against the project's test suite.\n- Before/after behavior verified for SAST fixes.\n\n**Please review carefully before merging.**`,
      head: "checkmarx-auto",
      base: repo.default_branch,
    });

    const prUrl = pr.html_url;

    await supabase
      .from("cm_scan")
      .update({
        status: "pr_opened",
        pr_url: prUrl,
        current_step: `PR opened: ${prUrl}`,
      })
      .eq("id", scanId);

    console.log(`[push-pr] scan ${scanId}: PR opened at ${prUrl}`);
  } finally {
    await ops.cleanup(workDir);
  }
}
